# docker-compose.yml
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_DATABASE=/var/www/html/database/database.sqlite
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
      - ./storage/logs:/var/log/apache2
