services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - DB_DATABASE=/var/www/html/database/database.sqlite
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
      - ./logs:/var/log/php-fpm
    ports:
      - "9000:9000"
    restart: unless-stopped
